services:
  cassandra1:
    image: cassandra:4.1
    container_name: cassandra1
    hostname: cassandra1
    networks:
      - cassandra-net
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "CassandraCluster"
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: RAC1
      CASSANDRA_SEEDS: "cassandra1,cassandra2,cassandra3"
      MAX_HEAP_SIZE: 1024M
      HEAP_NEWSIZE: 256M
    mem_limit: 1536m

  cassandra2:
    image: cassandra:4.1
    container_name: cassandra2
    hostname: cassandra2
    networks:
      - cassandra-net
    depends_on:
      - cassandra1
    environment:
      CASSANDRA_CLUSTER_NAME: "CassandraCluster"
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: RAC1
      CASSANDRA_SEEDS: "cassandra1,cassandra2,cassandra3"
      MAX_HEAP_SIZE: 1024M
      HEAP_NEWSIZE: 256M
    mem_limit: 1536m

  cassandra3:
    image: cassandra:4.1
    container_name: cassandra3
    hostname: cassandra3
    networks:
      - cassandra-net
    depends_on:
      - cassandra1
    environment:
      CASSANDRA_CLUSTER_NAME: "CassandraCluster"
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: RAC1
      CASSANDRA_SEEDS: "cassandra1,cassandra2,cassandra3"
      MAX_HEAP_SIZE: 1024M
      HEAP_NEWSIZE: 256M
    mem_limit: 1536m

networks:
  cassandra-net:
    driver: bridge
